### ISSUE TITLE
How to install this app

### ISSUE THREAD

**Issue by maddymathan** [Himank17Gupta/footprints-employee-tracking-application#1]
HI,

  Helpme out to install this app

**Comment by Himank17Gupta** [comment]
Hello, you can run npm install on your terminal, after deep clone of this react project into your local directory to install this project..
I think it should run perfect from there.

**Comment by Himank17Gupta** [comment]
I am closing this issue, since no further query was raised.
However you can give your valuable feedback and ask out query related to project anytime in future.
Thanks.
